name: Publish package to the Maven Central Repository
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: jboss-staging
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Check out default branch
        run: git checkout trunk
      - name: Set release version
        run: mvn -B versions:use-next-releases versions:commit
      - name: Publish package
        run: mvn -B clean verify deploy
        env:
          MAVEN_USERNAME: ${{ secrets.NEXUS_USER }}
          MAVEN_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      - name: Set release version
        run: mvn -B versions:use-next-snapshots versions:commit
      - name: Set git username
        run: git config --global user.name "GitHub Actions"
      - name: Set git email
        run: git config --global user.email "rhc-na-app-dev-practice@redhat.com"
      - name: Commit new snapshot version
        run: git commit pom.xml -m 'Update snapshot version after release'
      - name: Push new snapshot version
        run: git push origin trunk
