name: Publish package to the Maven Central Repository
on:
  push:
    branches:
      - trunk
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: trunk
          ssh-key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Set up JBoss Staging Repository
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: jboss-staging
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Set git user info
        run: |
              git config --global user.name "GitHub Actions"
              git config --global user.email "rhc-na-app-dev-practice@redhat.com"
      - name: Publish Release
        run: mvn -B release:prepare release:perform
        env:
          MAVEN_USERNAME: ${{ secrets.NEXUS_USER }}
          MAVEN_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
